---
- name: Install release RPM packages
  yum:
    name:
      - "{{ dst.repos.katello.release_rpm }}"
      - "{{ dst.repos.foreman.release_rpm }}"
      - "{{ dst.repos.puppet.release_rpm }}"
      - epel-release
    state: present

- name: Install foreman-scl release RPM package
  yum:
    name:
      - foreman-release-scl
    state: present


- name: System update
  include: system-update.yaml

- name: Install katello package
  yum:
    name: katello
    state: present

