---
- name: set admin interface ip in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ dst_vm.l3.interfaces.0.ip }}'
    line: "{{ dst_vm.l3.interfaces.0.ip }} {{dst_vm.name}}.{{dst_vm.domain_name}} {{dst_vm.name}} {{dst_vm.name}}.admin.{{dst_vm.domain_name}}"
    owner: root
    group: root
    mode: 0644
- name: set pxe interface ip in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ dst_vm.l3.interfaces.1.ip }}'
    line: "{{ dst_vm.l3.interfaces.1.ip }} {{dst_vm.name}}.pxe.{{dst_vm.domain_name}}"
    owner: root
    group: root
    mode: 0644
- name: foreman installer answers file
  template:
    src: "../../templates/dst/katello-answers.yaml.j2"
    dest: "/etc/foreman-installer/scenarios.d/katello-answers.yaml"
    owner: root
    group: root
    mode: 0600
- name: Katello initial deployment
  shell: "/usr/sbin/foreman-installer --scenario katello"
  args:
    creates: "/var/log/foreman-installer/katello.log"
- name: Katello custom CA certs update
  shell: "/usr/sbin/foreman-installer --scenario katello --certs-server-cert /etc/pki/katello-import/{{ dst_vm.name }}.{{ dst_vm.domain_name }}.crt --certs-server-cert-req /etc/pki/katello-import/{{ dst_vm.name }}.{{ dst_vm.domain_name }}.csr --certs-server-key /etc/pki/katello-import/{{ dst_vm.name }}.{{ dst_vm.domain_name }}.key --certs-server-ca-cert /etc/pki/katello-import/{{ cert_authorities.servers.name }}-bundle.crt --certs-update-server --certs-update-server-ca && touch /tmp/katello-install-done.txt"
  args:
    creates: "/tmp/katello-install-done.txt"