---
- name: manage created VMs in ansible inventory
  hosts: "localhost"
  tasks:

    - name: add VMs in inventory
      include: ../../tasks/extend-inventory.yaml

- name: katello packages deployment
  hosts: dst

  tasks:
  - name: Deploy katello
    include: ../../tasks/deploy-katello-packages.yaml

- name: create and fetch Katello cert
  hosts: pki
  tasks:
    - name: Katello cert create and fetch
      include: ../../tasks/generate_katello_certs.yaml

- name: configure Katello
  hosts: dst
  tasks:
    - name: Import katello certificate datas
      include: ../../tasks/import_katello_certs.yaml
    - name: Setup Katello
      include: ../../tasks/setup-katello.yaml