---        
- name: manage created VMs in ansible inventory
  hosts: "localhost"
  tasks:

    - name: add VMs in inventory
      include: ../../tasks/extend-inventory.yaml
  
- name: small PKI deployment
  hosts: pki
 
  tasks:
  - name: Deploy PKI
    include: ../../tasks/deploy-pki.yaml

  - name: Fetch cacert files
    include: ../../tasks/pki-get_ca_certs.yaml
