---
- name: manage created VMs in ansible inventory
  hosts: "localhost"
  tasks:

  - name: add pki VM in inventory
    add_host:
      name: "{{ pki_vm.name }}"
      groups: pki
      ansible_host: "{{ pki_vm.l3.interfaces.0.ip }}"
      ansible_user: root
      ansible_password: "{{ pki_vm.root_pw }}"
  - name: add dst VM in inventory
    add_host:
      name: "{{ dst_vm.name }}"
      groups: dst
      ansible_host: "{{ dst_vm.l3.interfaces.0.ip }}"
      ansible_user: root
      ansible_password: "{{ dst_vm.root_pw }}"

- name: manage created VMs
  hosts: pki:dst

  tasks:

  - name: Install additional standard packages
    yum:
      name:
      - yum-utils
      - vim-enhanced

  - name: System update
    include: ../tasks/system-update.yaml

  - name: inject ssh key
    authorized_key:
      state: present
      key: "{{ lookup('file', '../files/id_ed25519.pub') }}"
      user: "{{ ansible_user }}"

- name: configure chrony
  hosts: pki:dst
  roles:
    - role: linuxhq.chrony
  vars:
    chrony_commands:
      server:
        - 0.centos.pool.ntp.org iburst
        - 1.centos.pool.ntp.org iburst
        - 2.centos.pool.ntp.org iburst
      stratumweight: 0
      driftfile: /var/lib/chrony/drift
      rtcsync: True
      makestep: '1.0 3'
      bindcmdaddress: '0.0.0.0'
      bindcmdaddress: '::'
      keyfile: /etc/chrony.keys
      commandkey: '1'
      generatecommandkey: True
      logchange: '0.5'
      logdir: '/var/log/chrony'
      local: stratum 10
    chrony_sysconfig: '-F 1'

        
- name: small PKI deployment
  import_playbook: vms/pki.yaml
